GET http://localhost:5000/login

###
POST http://localhost:5000/signup
Content-Type: application/json

{
    "name": "dummmy ",
    "email": "hey@gmail.com",
    "password": "Dummmmy@"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "hey@gmail.com",
    "password": "Dummmmy@"
}

